### ISSUE TITLE
Naming bikeshedding

### ISSUE THREAD

**Issue by giordano** [giordano/PackageAnalyzer.jl#20]
Let's discuss here about names of everything, package and functions!

**Comment by ericphanson** [comment]
`analyze_from_registry` is kind of verbose as a name! And maybe it could/should be combined with `find_package` / `find_packages` so you just give it a package name and possibly a registry path, and it looks up the info itself.

**Comment by ericphanson** [comment]
it would also be good to come up with a better name for `directory` to describe a top-level directory or file; for example, I think `directory` here looks a bit odd:
```
  Row │ directory             language           sublanguage  total_code 
      │ String                Symbol             Union…       Int64      
──────┼──────────────────────────────────────────────────────────────────
    1 │ src                   Julia                              6938300
    2 │ plots                 SVG                                2995745
    3 │ test                  Julia                              2003802
    4 │ docs                  SVG                                1458939
    5 │ html                  HTML               JavaScript      1201695
    6 │ test                  XML                                 962022
```
(lines of code by directory/language/sublanguage for General)

**Comment by giordano** [comment]
I feel like some lightweight types like
```julia
struct Registry
    path::String
end

# `general_registry` would return an instance of `Registry`

struct RegistryEntry
    path::String
end

# `find_package` would return an instance of `RegistryEntry`
# `find_packages` would return a `Vector{RegistryEntry}`
```
for dispatch would simplify names.  And perhaps we can replace `analyze` with `check` or `check_package`.

Comments?

**Comment by ericphanson** [comment]
That sounds pretty good! Something like this?

Old signature | Old common usage | New signature | New common usage
-- | -- | -- | --
analyze(::String) | analyze(“.”) | check(::String) | check(“.”)
analyze(::String) | analyze(pkgdir(Pkg)) | check(::Module) | check(Pkg)
analyze_from_registry(::String) | analyze(find_package(“Name”)) | check(::RegistryEntry) | check(find_package(“Name”))
analyze_from_registry(paths::Vector{String}) | analyze(find_packages()) | check(::Registry) | check(find_packages())

**Comment by giordano** [comment]
Yes, exactly!

**Comment by ericphanson** [comment]
What about `check("Flux")` doing the `find_package` for you? I think it makes sense that the most common use-case gets the simplest API. That could be like:

Old signature | Old common usage | New signature | New common usage
-- | -- | -- | --
analyze(::String) | analyze(“.”) | check_path(::String) | check_path(“.”)
analyze(::String) | analyze(pkgdir(Pkg)) | check(::Module) | check(Pkg)
analyze_from_registry(::String) | analyze(find_package(“Flux”)) | check(::String) | check(“Flux”)
analyze_from_registry(::Vector{String}) | analyze(find_packages()) | check(::Vector{RegistryEntry}) | check(find_packages())

Semantics:

* `check(::String)`: it looks up the package in each installed registry and if the package is in both, takes the one with the latest version number (which is what Pkg does as well btw if you add a package with the same UUID which is in two registries)
* `check(r::RegistryEntry) = check_path(r.path)`. So then `find_packages("General")` returns a vector of `RegistryEntry`s like in https://github.com/giordano/AnalyzeRegistry.jl/issues/20#issuecomment-782769955 that hold the actual path, so there is no ambiguity.

Too magic?

Also, what about non-registered packages? Could be nice to be able to check by URL.

**Comment by giordano** [comment]
Yeah, I like it!

> Also, what about non-registered packages? Could be nice to be able to check by URL.

That's a though one because we don't have a base type to represent a URL, unless we cook our own.  Perhaps there are other packages providing a URL type, but we only need it for dispatch in a single function.

Maybe a method like `check(; url="...")`, or `check(; repo="...")`?  Not very happy though

**Comment by ericphanson** [comment]
Hm. Package names aren't allowed to have punctuation, so we could just check for them. The Pkg REPL mode does some fancy stuff along these lines: https://github.com/JuliaLang/Pkg.jl/blob/master/src/REPLMode/argument_parsers.jl, i.e.
```julia
julia> using Pkg

julia> Pkg.REPLMode.parse_package_identifier("Flux", add_or_develop=true)
PackageSpec(
  name = Flux
  version = *
)

julia> Pkg.REPLMode.parse_package_identifier("https://github.com/giordano/AnalyzeRegistry.jl", add_or_develop=true)
PackageSpec(
  version = *
  url/path = "https://github.com/giordano/AnalyzeRegistry.jl"
)
```
But we probably don't want to use Pkg internals. But we don't support versions or branches or commits so we could just check for a `/` or a `:` and assume it's a URL if we find those...

**Comment by giordano** [comment]
> Package names aren't allowed to have punctuation

That's an interesting point!  We can also check with `Base.isidentifier`, any URL (or local path, too) would fail the test

**Comment by giordano** [comment]
I'm not too convinced by the split `check_path`/`check`, this looks to me like a good use case for [`FilePathsBase.jl`](https://github.com/rofinn/FilePathsBase.jl).  What do you think?

**Comment by ericphanson** [comment]
> I'm not too convinced by the split check_path/check, this looks to me like a good use case for FilePathsBase.jl. What do you think?

I'm not sold on FilePathsBase, but I agree `check_path` vs `check` is kind of clunky. I think we can disambiguiate package names from paths pretty easily though; if it has a path separator then it's a path, otherwise it's a package name. That rule would mean we require `./Flux` instead of `Flux` to specify a directory named `Flux` in the current working directory. (I think Pkg.jl makes the opposite choice and regrets it, afaik).
